### ISSUE TITLE
使用maven下载依赖报错

### ISSUE THREAD

**Issue by Drewe-delu** [alldatacenter/alldata#700]
在IDEA中使用maven报错
<img width="1728" alt="image" src="https://github.com/alldatacenter/alldata/assets/53636846/51c7b990-60a6-4549-8701-bcb5673d1677">

**Comment by alldatafounder** [comment]
清除本地依赖，重新clean打包，alldata根目录进行打包编译

**Comment by lizhichao999** [comment]
相同的问题，解决了吗

**Comment by lizhichao999** [comment]
> 清除本地依赖，重新clean打包，alldata根目录进行打包编译

>mvn dependency:purge-local-repository
[INFO] Scanning for projects...
Downloading from focusin_nexus: https://dev-nexus.hysz.co/repository/maven-public/com/platform/services/0.4.x/services-0.4.x.pom
Downloading from hysz_nexus: https://dev-nexus.hysz.co/repository/maven-public/com/platform/services/0.4.x/services-0.4.x.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM com.platform:system-service-parent:0.4.x (D:\soft\alldata-alldata-0.4.6\studio\services\system-service-parent\pom.xml) points at com.platform:modules instead of com.platform:services, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.platform:system-service-parent:0.4.x: The following artifacts could not be resolved: com.platform:services:pom:0.4.x (absent): Could not find artifact com.platform:services:pom:0.4.x in focusin_nexus (https://dev-nexus.hysz.co/repository/maven-public/) and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[WARNING] 'parent.relativePath' of POM com.platform:file-service-parent:0.4.x (D:\soft\alldata-alldata-0.4.6\studio\services\file-service-parent\pom.xml) points at com.platform:modules instead of com.platform:services, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.platform:file-service-parent:0.4.x: The following artifacts could not be resolved: com.platform:services:pom:0.4.x (absent): com.platform:services:pom:0.4.x was not found in https://dev-nexus.hysz.co/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of focusin_nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[WARNING] 'parent.relativePath' of POM com.platform:email-service-parent:0.4.x (D:\soft\alldata-alldata-0.4.6\studio\services\email-service-parent\pom.xml) points at com.platform:modules instead of com.platform:services, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.platform:email-service-parent:0.4.x: The following artifacts could not be resolved: com.platform:services:pom:0.4.x (absent): com.platform:services:pom:0.4.x was not found in https://dev-nexus.hysz.co/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of focusin_nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[WARNING] 'parent.relativePath' of POM com.platform:quartz-service-parent:0.4.x (D:\soft\alldata-alldata-0.4.6\studio\services\quartz-service-parent\pom.xml) points at com.platform:modules instead of com.platform:services, please verify your project structure @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.platform:quartz-service-parent:0.4.x: The following artifacts could not be resolved: com.platform:services:pom:0.4.x (absent): com.platform:services:pom:0.4.x was not found in https://dev-nexus.hysz.co/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of focusin_nexus has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13
[WARNING] 'parent.relativePath' of POM com.platform:codegen-service-parent:0.4.x (D:\soft\alldata-alldata-0.4.6\studio\services\codegen-service-parent\pom.xml) points at com.platform:modules instead of com.platform:services, please verify your project structure @ line 5, column 13
